@API_URL = https://c7a7-58-187-59-169.ap.ngrok.io
@APP_VERSION = 1.0.0

curl --location --request GET {{API_URL}}/products \
--header 'Content-Type: application/json' \
--header 'version: {{APP_VERSION}}' \
--data-raw '{}'
#####

curl --location --request POST {{API_URL}}/products \
--header 'Content-Type: application/json' \
--header 'version: {{APP_VERSION}}' \
--data-raw '{
    "title": "my title 1",
    "description": "my description 1",
    "price": 100
    "installationId": "{{$guid}}"
}'